# ---------- BUILD STAGE ----------
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS builder
WORKDIR /build

# instalar certificados do sistema
RUN apt-get update && apt-get install -y ca-certificates

# copiar CA corporativo (se existir) e atualizar trust store
COPY corp-ca.crt /usr/local/share/ca-certificates/corp-ca.crt
RUN update-ca-certificates || true

# copiar csproj primeiro (melhor cache)
COPY Market.API.csproj ./

# restaurar dependências
RUN dotnet restore

# copiar restante do código
COPY . .

# publicar
RUN dotnet publish -c Release -o /app/publish


# ---------- RUNTIME STAGE ----------
FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app

RUN apt-get update && apt-get install -y ca-certificates

# copiar trust store do builder
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

# copiar app publicada
COPY --from=builder /app/publish .

EXPOSE 8000
ENTRYPOINT ["dotnet", "Market.API.dll"]