export const PERMISSIONS = {
  CREATE_USER: "CREATE_USER",
  DELETE_USER: "DELETE_USER",
  VIEW_USERS: "VIEW_USERS",
  UPDATE_USERS: "UPDATE_USERS",

  VIEW_DASHBOARD: "VIEW_DASHBOARD",

  VIEW_ACCOUNT: "VIEW_ACCOUNT",

  VIEW_PROFILES: "VIEW_PROFILES",
  CREATE_PROFILE: "CREATE_PROFILE",

  ADD_CUSTOMER: "ADD_CUSTOMER",
};

export const MODULES = {
  USERS: [
    PERMISSIONS.CREATE_USER,
    PERMISSIONS.DELETE_USER,
    PERMISSIONS.UPDATE_USERS,
    PERMISSIONS.VIEW_USERS,
  ],
  PROFILES: [PERMISSIONS.VIEW_PROFILES, PERMISSIONS.CREATE_PROFILE],
  CUSTOMERS: [PERMISSIONS.ADD_CUSTOMER],
};

export const ROLE_PERMISSION = {
  ADM: [
    ...MODULES.USERS,
    ...MODULES.PROFILES,
    ...MODULES.CUSTOMERS,
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_ACCOUNT,
  ],
  USER: [PERMISSIONS.VIEW_DASHBOARD, PERMISSIONS.VIEW_ACCOUNT],
};

export function hasPermission(user, permission) {
  if (!user) return false;

  const permissions = ROLE_PERMISSION[user.profile] || [];

  return permissions.includes(permission);
}
